#!/usr/bin/env bash

# start in a dir where you'd put your code projects
rm -fr repo_1

mkdir repo_1

cd repo_1

git init

cat <<README >"README.md"
This is the README for repo_1
tra la la la oh such fun
README

git add README.md

git commit -m "FEAT: initial commit" # conventional commit

cat <<GITIGNORE >".gitignore"
.tfstate
.vscode/
coverage/
node_modules/
lib/
.eslintcache
pids
*.pid
*.swp
*.seed
*.pid.lock
*.tsbuildinfo
.env
.DS_STORE
GITIGNORE

git add .gitignore

git commit -m "feat: add fitignore"

npm init -y

git add package.json

git commit -m "feat: run npm i"

