#!/usr/bin/env bash

# start in a dir where you'd put your code projects
rm -rf repo_2

mkdir repo_2

cd repo_2

git init

cat <<README >"README.md"
This is the README for repo_2
doo doo da da da doodily doo
README

git add README.md

git commit -m "FEAT: initial commit" # conventional commit

cat <<GITIGNORE >".gitignore"
.tfstate
.vscode/
coverage/
node_modules/
lib/
.eslintcache
pids
*.pid
*.swp
*.seed
*.pid.lock
*.tsbuildinfo
.env
.DS_STORE
GITIGNORE

git add .gitignore

git commit -m "feat: add fitignore"

npm init -y

git add package.json

git commit -m "feat: run npm init"

touch index.html && touch DS_Store

git add .

git commit -m "feat: add index"

